@startuml

title __INTERFACE's Class Diagram__\n

  namespace s  {
    interface ICarModel {
        {abstract} + addObserver()
        {abstract} + brake()
        {abstract} + gas()
        {abstract} + lowerRamp()
        {abstract} + raiseRamp()
        {abstract} + setTurboOff()
        {abstract} + setTurboOn()
        {abstract} + startEngines()
        {abstract} + stopEngines()
        {abstract} + update()
    }
  }
  

  namespace s  {
    interface IController {
        {abstract} + init()
    }
  }
  

  namespace s  {
    interface IDriveable {
        {abstract} + brake()
        {abstract} + gas()
        {abstract} + getCurrentSpeed()
        {abstract} + startEngine()
        {abstract} + stopEngine()
    }
  }
  

  namespace s  {
    interface IFerryCargo {
    }
  }
  

  namespace s  {
    interface IFrame {
        {abstract} + paintComponent()
    }
  }
  

  namespace s  {
    interface IMovable {
        {abstract} + move()
        {abstract} + turnLeft()
        {abstract} + turnRight()
    }
  }
  

  namespace s  {
    interface IPositionable {
        {abstract} + getPos()
        {abstract} + getPosX()
        {abstract} + getPosY()
        {abstract} + setPos()
    }
  }
  

  namespace s  {
    interface IPositionablePicture {
        {abstract} + getImage()
        {abstract} + getPosition()
    }
  }
  

  namespace s  {
    interface ISignalObserver {
        {abstract} + actOnAction()
        {abstract} + getGasAmount()
        {abstract} + lowerRampAction()
        {abstract} + raiseRampAction()
        {abstract} + setBrakeAction()
        {abstract} + setGasAction()
        {abstract} + setTurboOffAction()
        {abstract} + setTurboOnAction()
        {abstract} + startEngineAction()
        {abstract} + stopEngineAction()
    }
  }
  

  namespace s  {
    interface ITransporter {
        {abstract} + lowerRamp()
        {abstract} + raiseRamp()
    }
  }
  

  namespace s  {
    interface ITruckCargo {
    }
  }
  

  namespace s  {
    interface ITurbo {
        {abstract} + setTurboOff()
        {abstract} + setTurboOn()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
